In [63]:
import pandas as pd

In [64]:
df = pd.read_csv("./My Data/data.csv")

In [65]:
df = df.drop(list(df)[0], axis = 1)

In [66]:
df.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Free Cash Flow growth,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF
0,ANTE,2018-12-31,11036000.0,0.065662,NaN,-2138000.0,NaN,NaN,18346500.0,-13403000.0,...,NaN,-0.2636,0.0,-0.4230,NaN,NaN,NaN,NaN,2.65,3.956029
1,ANTE,2018-09-30,10356000.0,-0.108625,NaN,-2138000.0,NaN,NaN,18346500.0,-13403000.0,...,NaN,-0.2636,0.0,-0.4230,NaN,NaN,NaN,NaN,1.70,3.054594
2,ANTE,2018-06-30,11618000.0,-0.325437,NaN,-1904000.0,NaN,NaN,18020500.0,-10691000.0,...,NaN,-0.9474,0.0,-0.6146,NaN,NaN,NaN,NaN,2.65,3.014265
3,ANTE,2018-03-31,17223000.0,-0.738228,NaN,-1904000.0,NaN,NaN,18020500.0,-10691000.0,...,NaN,-0.4020,0.0,-0.5592,NaN,NaN,NaN,NaN,3.35,3.714265
4,ANTE,2017-12-31,65794000.0,0.000000,NaN,-7356500.0,NaN,NaN,28521000.0,-21986500.0,...,NaN,1.5717,0.0,-0.3509,NaN,NaN,NaN,NaN,6.00,6.010755

In [67]:
def generateTargets(df):
    df["Target"] = df["Market Cap"].shift(-1)
    return df[:-1]

In [68]:
df = df.dropna(subset=["Company", "Date"])

In [69]:
df = df.sort_values(["Company", "Date"])

In [70]:
df1 = df.groupby("Company").apply(
    lambda group: generateTargets(group)
)

In [71]:
df1 = df1.droplevel(0)

In [72]:
df1.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target
7145,A,2009-07-31,1.057000e+09,-0.268000,518000000.0,539000000.0,153000000.0,387000000.0,540000000.0,-1000000.0,...,-0.2852,-0.1528,-0.1284,NaN,NaN,-0.1000,-0.0675,18.48,0.000000,7.140368e+09
7144,A,2009-10-31,1.167000e+09,0.104068,533000000.0,634000000.0,150000000.0,413000000.0,563000000.0,71000000.0,...,-0.2273,-0.1455,0.0863,0.0193,0.3671,-0.1176,0.0123,20.69,32.451397,8.075444e+09
7143,A,2010-01-31,1.213000e+09,0.039417,553000000.0,660000000.0,149000000.0,417000000.0,566000000.0,94000000.0,...,-0.0032,-0.1634,0.0575,0.0161,0.3208,-0.1183,0.0530,23.15,34.780264,8.059576e+09
7142,A,2010-04-30,1.271000e+09,0.047815,560000000.0,711000000.0,150000000.0,407000000.0,557000000.0,154000000.0,...,0.1757,-0.1020,0.1811,0.0722,0.3435,-0.1176,0.0000,23.15,35.271358,6.891646e+09
7141,A,2010-07-31,1.384000e+09,0.088906,659000000.0,725000000.0,154000000.0,456000000.0,610000000.0,115000000.0,...,0.4522,0.2049,0.3845,0.1194,0.7083,0.0065,0.1783,19.80,30.944537,8.676577e+09

In [73]:
df1 = df1.dropna()

In [74]:
df1.to_csv("./My Data/final_cleaned_data.csv")

In [75]:
df1["Test"] = 100*(df1["Target"] - df1["Market Cap"])/df1["Market Cap"]

In [76]:
df1['Label'] = 1
df1.loc[df1['Test'] > 5, 'Label'] = 2
df1.loc[df1['Test'] < -5, 'Label'] = 0

# Label = 2 indicates buy
# Label = 1 indicates hold
# Label = 0 indicates sell

In [77]:
df1["Target"].head()

7144    8.075444e+09
7143    8.059576e+09
7142    6.891646e+09
7141    8.676577e+09
7140    1.030994e+10
Name: Target, dtype: float64

In [78]:
df1["Market Cap"].head()

7144    7.140368e+09
7143    8.075444e+09
7142    8.059576e+09
7141    6.891646e+09
7140    8.676577e+09
Name: Market Cap, dtype: float64

In [79]:
df1.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target,Test,Label
7144,A,2009-10-31,1.167000e+09,0.104068,533000000.0,634000000.0,150000000.0,413000000.0,563000000.0,71000000.0,...,0.0863,0.0193,0.3671,-0.1176,0.0123,20.69,32.451397,8.075444e+09,13.095621,2
7143,A,2010-01-31,1.213000e+09,0.039417,553000000.0,660000000.0,149000000.0,417000000.0,566000000.0,94000000.0,...,0.0575,0.0161,0.3208,-0.1183,0.0530,23.15,34.780264,8.059576e+09,-0.196501,1
7142,A,2010-04-30,1.271000e+09,0.047815,560000000.0,711000000.0,150000000.0,407000000.0,557000000.0,154000000.0,...,0.1811,0.0722,0.3435,-0.1176,0.0000,23.15,35.271358,6.891646e+09,-14.491212,0
7141,A,2010-07-31,1.384000e+09,0.088906,659000000.0,725000000.0,154000000.0,456000000.0,610000000.0,115000000.0,...,0.3845,0.1194,0.7083,0.0065,0.1783,19.80,30.944537,8.676577e+09,25.899935,2
7140,A,2010-10-31,1.576000e+09,0.138728,742000000.0,834000000.0,159000000.0,472000000.0,631000000.0,203000000.0,...,0.2738,0.2844,0.2706,0.0600,0.1429,25.05,37.172862,1.030994e+10,18.824973,2

In [80]:
df1 = df1.drop("Test", axis=1)

In [81]:
normalized = pd.DataFrame()
norm_ratios = dict()

In [83]:
for k in list(df1.keys()):
    if k != "Company" and k != "Date" and k != "Label":
        normalized[k] = (df1[k] - df1[k].mean()) / df1[k].std()
        norm_ratios[k] = df1[k].mean()
    else:
        normalized[k] = df1[k]

In [84]:
normalized

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target,Label
7144,A,2009-10-31,-0.024968,-0.004806,-0.036315,0.087302,0.476645,0.233879,0.157506,-0.113755,...,-0.006069,-0.003855,0.001308,-0.007283,-0.004934,-0.004106,-0.014110,-0.005107,-0.005907,2
7143,A,2010-01-31,-0.017249,-0.004812,-0.030817,0.097868,0.472680,0.238041,0.159408,-0.086932,...,-0.006071,-0.003855,0.000873,-0.007291,-0.004934,-0.004106,-0.013945,-0.005107,-0.005907,1
7142,A,2010-04-30,-0.007516,-0.004811,-0.028892,0.118593,0.476645,0.227636,0.153701,-0.016959,...,-0.006062,-0.003855,0.008501,-0.007287,-0.004934,-0.004106,-0.013945,-0.005107,-0.005927,0
7141,A,2010-07-31,0.011447,-0.004807,-0.001676,0.124283,0.492502,0.278619,0.187306,-0.062441,...,-0.006018,-0.003854,0.014919,-0.007225,-0.004921,-0.004104,-0.014169,-0.005107,-0.005896,2
7140,A,2010-10-31,0.043667,-0.004802,0.021141,0.168579,0.512323,0.295267,0.200621,0.040186,...,-0.006005,-0.003855,0.037356,-0.007299,-0.004915,-0.004105,-0.013817,-0.005107,-0.005868,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123581,ZYXI,2018-06-30,-0.219533,-0.004806,-0.182477,-0.167809,-0.118001,-0.192167,-0.197226,-0.193390,...,-0.005772,-0.003850,0.784016,-0.007499,-0.004921,-0.004099,-0.015293,-0.005108,-0.006044,1
123580,ZYXI,2018-09-30,-0.219440,-0.004809,-0.182391,-0.167709,-0.118001,-0.192019,-0.197136,-0.193268,...,-0.005871,-0.003853,0.619906,-0.007504,-0.004921,-0.004102,-0.015293,-0.005108,-0.006044,1
123579,ZYXI,2018-12-31,-0.219237,-0.004801,-0.182339,-0.167296,-0.118001,-0.191025,-0.196530,-0.193198,...,-0.005906,-0.003853,0.123034,-0.005763,-0.004921,-0.004101,-0.015239,-0.005108,-0.006043,2
123578,ZYXI,2019-03-31,-0.219261,-0.004817,-0.182352,-0.167334,-0.118001,-0.190473,-0.196194,-0.193926,...,-0.005995,-0.003853,0.165527,-0.001595,-0.004921,-0.004102,-0.015124,-0.005108,-0.006040,2
123577,ZYXI,2019-06-30,-0.219076,-0.004804,-0.182307,-0.166954,-0.118001,-0.189840,-0.195808,-0.193543,...,-0.005823,-0.003853,0.117228,0.005507,-0.004921,-0.004100,-0.014935,-0.005108,-0.006040,1

In [85]:
pd.DataFrame(norm_ratios, index=[0]).to_csv("./My Data/norm_ratios.csv", index=False)
normalized.reset_index(drop=True).to_csv("./My Data/normalized_data.csv", index=False)

In [86]:
test = normalized[normalized["Date"] >= "2018"].reset_index(drop=True)

In [87]:
other = normalized[normalized["Date"] <= "2018"].reset_index(drop=True)
other = other.sample(frac=1).reset_index(drop=True)

In [88]:
length = len(other)

train_ratio = 0.95
train_samples = (int)(length*train_ratio)

In [89]:
train = other[0:train_samples]
val = other[train_samples:]

In [90]:
train.to_csv("./My Data/train.csv", index=False)
val.to_csv("./My Data/val.csv", index=False)
test.to_csv("./My Data/test.csv", index=False)