In [2]:
import pandas as pd

In [12]:
df = pd.read_csv("data.csv")

In [16]:
df = df.drop(list(df)[0], axis = 1)

In [17]:
df.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Free Cash Flow growth,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF
0,ANTE,2018-12-31,11036000.0,0.065662,NaN,-2138000.0,NaN,NaN,18346500.0,-13403000.0,...,NaN,-0.2636,0.0,-0.4230,NaN,NaN,NaN,NaN,2.65,3.956029
1,ANTE,2018-09-30,10356000.0,-0.108625,NaN,-2138000.0,NaN,NaN,18346500.0,-13403000.0,...,NaN,-0.2636,0.0,-0.4230,NaN,NaN,NaN,NaN,1.70,3.054594
2,ANTE,2018-06-30,11618000.0,-0.325437,NaN,-1904000.0,NaN,NaN,18020500.0,-10691000.0,...,NaN,-0.9474,0.0,-0.6146,NaN,NaN,NaN,NaN,2.65,3.014265
3,ANTE,2018-03-31,17223000.0,-0.738228,NaN,-1904000.0,NaN,NaN,18020500.0,-10691000.0,...,NaN,-0.4020,0.0,-0.5592,NaN,NaN,NaN,NaN,3.35,3.714265
4,ANTE,2017-12-31,65794000.0,0.000000,NaN,-7356500.0,NaN,NaN,28521000.0,-21986500.0,...,NaN,1.5717,0.0,-0.3509,NaN,NaN,NaN,NaN,6.00,6.010755

In [18]:
def generateTargets(df):
    df["Target"] = df["Market Cap"].shift(-1)
    return df[:-1]

In [19]:
df = df.dropna(subset=["Company", "Date"])

In [20]:
df = df.sort_values(["Company", "Date"])

In [21]:
df1 = df.groupby("Company").apply(
    lambda group: generateTargets(group)
)

In [25]:
df1 = df1.droplevel(0)

In [26]:
df1.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target
7145,A,2009-07-31,1.057000e+09,-0.268000,518000000.0,539000000.0,153000000.0,387000000.0,540000000.0,-1000000.0,...,-0.2852,-0.1528,-0.1284,NaN,NaN,-0.1000,-0.0675,18.48,0.000000,7.140368e+09
7144,A,2009-10-31,1.167000e+09,0.104068,533000000.0,634000000.0,150000000.0,413000000.0,563000000.0,71000000.0,...,-0.2273,-0.1455,0.0863,0.0193,0.3671,-0.1176,0.0123,20.69,32.451397,8.075444e+09
7143,A,2010-01-31,1.213000e+09,0.039417,553000000.0,660000000.0,149000000.0,417000000.0,566000000.0,94000000.0,...,-0.0032,-0.1634,0.0575,0.0161,0.3208,-0.1183,0.0530,23.15,34.780264,8.059576e+09
7142,A,2010-04-30,1.271000e+09,0.047815,560000000.0,711000000.0,150000000.0,407000000.0,557000000.0,154000000.0,...,0.1757,-0.1020,0.1811,0.0722,0.3435,-0.1176,0.0000,23.15,35.271358,6.891646e+09
7141,A,2010-07-31,1.384000e+09,0.088906,659000000.0,725000000.0,154000000.0,456000000.0,610000000.0,115000000.0,...,0.4522,0.2049,0.3845,0.1194,0.7083,0.0065,0.1783,19.80,30.944537,8.676577e+09

In [27]:
df1 = df1.dropna()

In [28]:
df1.to_csv("final_cleaned_data.csv")

In [29]:
df1["Test"] = 100*(df1["Target"] - df1["Market Cap"])/df1["Market Cap"]

In [30]:
df1['Label'] = 1
df1.loc[df1['Test'] > 5, 'Label'] = 2
df1.loc[df1['Test'] < -5, 'Label'] = 0

# Label = 2 indicates buy
# Label = 1 indicates hold
# Label = 0 indicates sell

In [44]:
df1["Target"].head()

7144    8.075444e+09
7143    8.059576e+09
7142    6.891646e+09
7141    8.676577e+09
7140    1.030994e+10
Name: Target, dtype: float64

In [45]:
df1["Market Cap"].head()

7144    7.140368e+09
7143    8.075444e+09
7142    8.059576e+09
7141    6.891646e+09
7140    8.676577e+09
Name: Market Cap, dtype: float64

In [46]:
df1.head()

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target,Test,Label
7144,A,2009-10-31,1.167000e+09,0.104068,533000000.0,634000000.0,150000000.0,413000000.0,563000000.0,71000000.0,...,0.0863,0.0193,0.3671,-0.1176,0.0123,20.69,32.451397,8.075444e+09,13.095621,2
7143,A,2010-01-31,1.213000e+09,0.039417,553000000.0,660000000.0,149000000.0,417000000.0,566000000.0,94000000.0,...,0.0575,0.0161,0.3208,-0.1183,0.0530,23.15,34.780264,8.059576e+09,-0.196501,1
7142,A,2010-04-30,1.271000e+09,0.047815,560000000.0,711000000.0,150000000.0,407000000.0,557000000.0,154000000.0,...,0.1811,0.0722,0.3435,-0.1176,0.0000,23.15,35.271358,6.891646e+09,-14.491212,0
7141,A,2010-07-31,1.384000e+09,0.088906,659000000.0,725000000.0,154000000.0,456000000.0,610000000.0,115000000.0,...,0.3845,0.1194,0.7083,0.0065,0.1783,19.80,30.944537,8.676577e+09,25.899935,2
7140,A,2010-10-31,1.576000e+09,0.138728,742000000.0,834000000.0,159000000.0,472000000.0,631000000.0,203000000.0,...,0.2738,0.2844,0.2706,0.0600,0.1429,25.05,37.172862,1.030994e+10,18.824973,2

In [47]:
df1 = df1.drop("Test", axis=1)

In [48]:
normalized = pd.DataFrame()
norm_ratios = dict()

In [49]:
for k in list(df1.keys()):
    if k != "Company" and k != "Date" and k != "Label":
        normalized[k] = df1[k] / df1[k].mean()
        norm_ratios[k] = df1[k].mean()
    else:
        normalized[k] = df1[k]

In [52]:
normalized

,Company,Date,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,...,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Stock Price,DCF,Target,Label
7144,A,2009-10-31,0.886921,0.002115,0.801387,1.512495,5.039330,2.194246,1.789650,0.421261,...,-0.003473,0.000049,1.993956,0.008460,-0.002455,0.000029,0.089527,0.000206,0.022941,2
7143,A,2010-01-31,0.921881,0.000801,0.831457,1.574522,5.005735,2.215497,1.799186,0.557726,...,-0.003900,0.000032,1.663352,0.007393,-0.002469,0.000126,0.100172,0.000221,0.022896,1
7142,A,2010-04-30,0.965962,0.000972,0.841982,1.696190,5.039330,2.162368,1.770577,0.913722,...,-0.002434,0.000102,7.459256,0.007916,-0.002455,0.000000,0.100172,0.000224,0.019578,0
7141,A,2010-07-31,1.051842,0.001807,0.990833,1.729589,5.173713,2.422702,1.939052,0.682325,...,0.004890,0.000217,12.335667,0.016324,0.000136,0.000423,0.085676,0.000197,0.024649,2
7140,A,2010-10-31,1.197762,0.002820,1.115626,1.989623,5.341690,2.507709,2.005806,1.204452,...,0.007091,0.000155,29.382442,0.006236,0.001252,0.000339,0.108393,0.000236,0.029289,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123581,ZYXI,2018-06-30,0.005755,0.002061,0.002000,0.014894,0.000000,0.018744,0.011215,0.016109,...,0.045587,0.001263,596.688806,-0.020972,0.000000,0.001637,0.013154,0.000021,0.000270,1
123580,ZYXI,2018-09-30,0.006180,0.001498,0.002467,0.015483,0.000000,0.019499,0.011666,0.016732,...,0.029200,0.000690,471.999391,-0.021608,0.000000,0.001059,0.013198,0.000021,0.000270,1
123579,ZYXI,2018-12-31,0.007096,0.003015,0.002753,0.017907,0.000000,0.024578,0.014705,0.017088,...,0.023358,0.000653,94.480463,0.215360,0.000000,0.001271,0.016659,0.000027,0.000440,2
123578,ZYXI,2019-03-31,0.006989,-0.000307,0.002682,0.017682,0.000000,0.027394,0.016390,0.013385,...,0.008673,0.000580,126.766023,0.782888,0.000000,0.000947,0.024102,0.000037,0.000878,2
123577,ZYXI,2019-06-30,0.007826,0.002434,0.002929,0.019918,0.000000,0.030629,0.018326,0.015332,...,0.037181,0.000518,90.068964,1.749732,0.000000,0.001505,0.036304,0.000055,0.000877,1

In [53]:
pd.DataFrame(norm_ratios, index=[0]).to_csv("norm_ratios.csv", index=False)
normalized.reset_index(drop=True).to_csv("normalized_data.csv", index=False)

In [54]:
test = normalized[normalized["Date"] >= "2018"].reset_index(drop=True)

In [55]:
other = normalized[normalized["Date"] <= "2018"].reset_index(drop=True)
other = other.sample(frac=1).reset_index(drop=True)

In [56]:
length = len(other)

train_ratio = 0.95
train_samples = (int)(length*train_ratio)

In [57]:
train = other[0:train_samples]
val = other[train_samples:]

In [61]:
train.to_csv("train.csv", index=False)
val.to_csv("val.csv", index=False)
test.to_csv("test.csv", index=False)